### ISSUE TITLE
Doesn't currently compile

### ISSUE THREAD

**Issue by ncw** [natefinch/gorram#12]
Doesn't currently compile

```
$ go install npf.io/gorram
# npf.io/gorram
./main.go:21: undefined: cli.Run
```

```
$ go version
go version go1.7.1 linux/amd64
```

**Comment by natefinch** [comment]
Gah, missed adding a file. Thanks.  This is fixed now.  That proves I need to set up CI so that doesn't happen again

**Comment by ncw** [comment]
Thanks for fixing it!  Cool tool :-)

**Comment by natefinch** [comment]
Awesome.  Glad you like it.   Suggestions welcome :)
