### ISSUE TITLE
format time as RFC3339

### ISSUE THREAD

**Issue by yene** [natefinch/gorram#24]
I use gorram to print the current time, is it possible to format it as RFC3339?

**Comment by natefinch** [comment]
I am working on enabling using a text/template to format the output, which should enable you to do that.

**Comment by natefinch** [comment]
This now works, though it's not the shortest invocation ever:
$ gorram -t '{{.Format "2006-01-02T15:04:05Z07:00"}}' time Now
2016-10-11T09:05:40-04:00

(make sure to run at least once with -r to regenerate the cached script to get the new behavior)
