### ISSUE TITLE
Doesn't handle package name != dir

### ISSUE THREAD

**Issue by natefinch** [natefinch/gorram#6]
Assumes package name is always the same as the last part of the import path

**Comment by raff** [comment]
Maybe you could add a --import or -I option and do something like:
`gorram -I gopkg.in/yaml.v2 yaml.Marshal(map[string]string{"x":1,"y",2})`

**Comment by natefinch** [comment]
I actually already have a fix for this.. .we can get the package name from the package when we parse it, I just wasn't doing that before.

**Comment by natefinch** [comment]
fixed by cd6047c
